# -*- coding: utf-8 -*-
"""Seasonal Agriculture Performance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TODGNG5GmOfbXUmZhKHqpfYOr94xA60Z
"""

Seasonal Agriculture Performance Analysis-

Major Data Analysis Project

Domain:Agriculture
Project Theme:Seasonal Agriculture Performance Tools:Python,Numpy,Matplotlib,Pandas,Seaborn

Project Goal---
Investigate how agricultural performance varies across seasons and identify meaningful patterns, trends,realtionships and differences in the available data.

PROBLEM STATEMENT-

Agricultural activities are influenced by seasonal variations in environmental conditions,
farming practices, resource availability and market conditions. As a result, agricultural
performance may differ from one season to another.
However, raw agricultural data does not clearly explain how agricultural performance changes
across seasons or what patterns can be observed in different seasonal conditions.
The problem is to analyze the given agricultural dataset and investigate seasonal differences
in agricultural performance by identifying meaningful patterns, trends, relationships and
variations within the available data.

PROJECT OBJECTIVES-

The primary objective of this project is to analyze agricultural data from different seasons
and identify meaningful patterns, trends, relationships and differences in agricultural
performance.
Students should independently:
1. Explore and understand the dataset.
2. Clean and prepare the data for analysis.
3. Examine how agricultural performance varies across seasons.
4. Identify important seasonal patterns and trends.
5. Investigate relationships between seasonal conditions and agricultural outcomes.
6. Compare relevant groups within different seasons.
7. Identify significant differences or unusual patterns.
8. Apply appropriate statistical and visualization techniques.
9. Interpret findings based on evidence from the dataset.
10. Develop meaningful conclusions and data-driven recommendations.

Dataset-

The dataset represents agricultural activities carried out across different seasons,
geographical areas and farming conditions. It contains information related to farming
practices, environmental conditions, crop production, resource usage and economic
performance.
The dataset provides students with an opportunity to explore how agricultural performance
changes across seasons and to identify meaningful patterns and differences through data
analysis.

Dataset file: /content/seasonal_agriculture_performance_dataset.csv

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")
# Load the datset
df = pd.read_csv('/content/seasonal_agriculture_performance_dataset.csv')
print("datset loaded successfully")

df.head(5)

df.tail(5)

df.shape

# Datatypes and Non-Null Counts
df.info()

df.columns

df.describe(include="object")

# Random sample of records
df.sample(5, random_state = 42)

df.isnull().sum()

# Columns names
print(df.columns.tolist())

# Missing Values
missing = df.isnull().sum().sort_values(ascending=False)
missing_percentage = (df.isnull().mean()*100).sort_values(ascending=False)

missing_summary=pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_percentage.round(2)
})
missing_summary[missing_summary["Missing_Count"]>0]

# Visulaize missing values
plt.figure(figsize=(12,5))
missing_plot = missing[missing > 0]
if len(missing_plot)>0:
  sns.barplot(x=missing_plot.index, y=missing_plot.values)
  plt.xticks(rotation=60, ha="right")
  plt.ylabel("column")
  plt.title("Missing values by column")
  plt.tight_layout()
  plt.show()
else:
  print("No missing values found")

# Duplicate records
duplicate_count = df.duplicated().sum()
print("Number of dupliate rows:", duplicate_count)

# Remove duplicate rows
df = df.drop_duplicates().reset_index(drop=True)
print("Shape after removing duplicates: ",df.shape)

# Check datatypes again
# df.dtypes

# Check unique values for categorical columns
categorical_columns = df.select_dtypes(include="object").columns
for col in categorical_columns:
  print(f"\n{col}:")
  print(df[col].dropna().unique()[:20])

# Check missing values after duplicate removal
df.isnull().sum().sort_values(ascending=False).head(10)

numeric_columns = df.select_dtypes(include=np.number).columns
for col in numeric_columns:
  if df[col].isnull().sum()>0:
    df[col]=df[col].fillna(df[col].median())
print("Remaining missing values:",df.isnull().sum().sum())

numeric_columns = df.select_dtypes(include=np.number).columns.tolist()
categorical_columns = df.select_dtypes(include="object").columns.tolist()
print("Numerical columns:")
print(numeric_columns)
print("\nCategorical columns:")
print(categorical_columns)

# Desciptive statstics
stats = df[numeric_columns].describe().T
stats["range"] = stats["max"] - stats["min"]
stats["IQR"] = stats["75%"] - stats["25%"]
stats

# Median and Standard Deviation
statistical_summary = pd.DataFrame({
    "Mean": df[numeric_columns].mean(),
    "Median": df[numeric_columns].median(),
    "Std_Dev": df[numeric_columns].std(),
    "Min": df[numeric_columns].min(),
    "Max": df[numeric_columns].max()
})
statistical_summary

# Seasonal Descriptive Summary
season_summary = df.groupby("Season")[numeric_columns].agg(["mean", "median", "std"])
season_summary

# Univariate: Season distribution
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(7, 5))
sns.countplot(data=df, x="Season")
plt.title("Distribution of Records by season")
plt.xlabel("Season")
plt.ylabel("Number of records")
plt.tight_layout()
plt.show()

# Univariate: Crop distribution
plt.figure(figsize=(10,5))
sns.countplot(data=df, x="Crop", order=df["Crop"].value_counts().index)
plt.xticks(rotation=45,ha="right")
plt.title("Distribution of Crops")
plt.xlabel("Crop")
plt.ylabel("Number of Records")
plt.tight_layout()
plt.show()

#  Univariate: yield Distribution
plt.figure(figsize=(8,5))
sns.histplot(data=df,x="Yield_Tonnes_Ha", kde = True)
plt.title("Distribution of Agricultural Yield")
plt.xlabel("Yield (tonnes/ha)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Univariate: Profit distribution
plt.figure(figsize=(8,5))
sns.histplot(data=df, x="Profit_INR", kde=True)
plt.title("Distribution of Farm Profit")
plt.xlabel("Profit (INR)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Univariate: Rainfall Distribution
plt.figure(figsize=(8,5))
sns.histplot(data=df, x="Rainfall_mm", kde=True)
plt.title("Distribution of Rainfall")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Univariate: Boxplot for yield
plt.figure(figsize=(8,5))
sns.boxplot(data=df, x="Yield_Tonnes_Ha")
plt.title("Yield Distribution and Potential Outliers")
plt.ylabel("Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
df = pd.read_csv('/content/seasonal_agriculture_performance_dataset.csv')
plt.figure(figsize=(7, 7))
df['Season'].value_counts().plot.pie(autopct= '%1.1f%%', startangle=90, cmap='viridis')
plt.title('Distribution of Records by Season')
plt.ylabel('')
plt.tight_layout()
plt.show()

import pandas as pd

# Automatically fetch only the numerical columns that exist in df
numeric_columns = df.select_dtypes(include=['number']).columns

# IQR based outlier summary for numerical columns
outlier_summary = []

for col in numeric_columns:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    # Count outliers safely
    count = ((df[col] < lower) | (df[col] > upper)).sum()

    outlier_summary.append({
        "Column": col,
        "Lower_Bound": lower,
        "Upper_Bound": upper,
        "Outlier_Count": count,
        "Outlier_Percentage": round((count / len(df)) * 100, 2) if len(df) > 0 else 0
    })

# Convert list to DataFrame and sort
outlier_summary_df = pd.DataFrame(outlier_summary)

if not outlier_summary_df.empty:
    outlier_summary_df = outlier_summary_df.sort_values(by="Outlier_Count", ascending=False)

outlier_summary_df

# Bivariate: Season vs Yield
import seaborn as sns
plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="Season", y="Yield_Tonnes_Ha")
plt.title("Yield Distribution across Seasons")
plt.xlabel("Season")
plt.ylabel("Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

# Bivariate: Rainfall vs yield
plt.figure(figsize=(8,5))
sns.scatterplot(data=df, x="Rainfall_mm", y="Yield_Tonnes_Ha", alpha=0.5)
plt.title("Relationship between Rainfall and Yield")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(data=df, x="Season", y="Profit_INR", errorbar= None)
plt.title("Average Profit across Seasons (Bar Plot)")
plt.xlabel("Season")
plt.ylabel("Average Profit (INR)")
plt.tight_layout()
plt.show()

# Multivariate: Season, crop and yield
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x="Crop", y="Yield_Tonnes_Ha", hue="Season")
plt.xticks(rotation=45, ha="right")
plt.title("Yield Distribution by Crop and Season")
plt.xlabel("Crop")
plt.ylabel("Yield (tonnes/ha)")
plt.legend(title="Season")
plt.tight_layout()
plt.show()

selected_columns = ['Avg_Temperature_C','Rainfall_mm','Humidity_pct','Yield_Tonnes_Ha','Profit_INR', 'Season']
sns.pairplot(df[selected_columns], hue='Season', palette='viridis', plot_kws={'alpha': 0.6})
plt.suptitle('Pair Plot of Environmental and Performance Metrics by Season', y=1.02)
plt.tight_layout()
plt.show()

# Multivariate: Season, irrigationcand yield
plt.figure(figsize=(12,6))
sns.boxplot(data=df, x="Irrigation_Method", y="Yield_Tonnes_Ha", hue="Season")
plt.title("Yield by irrigation Method and Season ")
plt.xlabel("Irrigation Method")
plt.ylabel("Yield (tonnes/ha)")
plt.legend(title="Season")
plt.tight_layout()
plt.show()

# Multivariate: Rainfall, Yield and Season
plt.figure(figsize=(10,6))
sns.scatterplot (
    data=df,
    x="Rainfall_mm",
    y="Yield_Tonnes_Ha",
    hue="Season",
    size="Farm_Area_Hectares",
    sizes=(20, 180),
    alpha=0.65
)
plt.title("Rainfall, Yield and Seasonal Differences")
plt.xlabel("Rainfall(mm)")
plt.ylabel("Yield (tonnes/ha)")
plt.tight_layout()
plt.show()

# Multivariate: Profit, Yield and Season
plt.figure(figsize=(10,6))
sns.scatterplot (
    data=df,
    x="Yield_Tonnes_Ha",
    y="Profit_INR",
    hue="Season",
    size="Farm_Area_Hectares",
    sizes=(20, 180),
    alpha=0.65
)
plt.title("Yield, Profit and Seasonal Differences")
plt.xlabel("Yield (tonnes/ha)")
plt.ylabel("Profit (INR)")
plt.tight_layout()
plt.show()

# Correlation heatmap for numerical variables
plt.figure(figsize=(16, 12))

# Select numeric columns dynamically and calculate correlation
corr = df.select_dtypes(include=['number']).corr()

# Draw the heatmap
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    linewidths=0.5
)

plt.title("Correlation Matrix of Numerical Variables")
plt.tight_layout()
plt.show()

# General seasonal summary

season_metrics = df.groupby("Season").agg(
    Records=("Farm_ID", "count"),
    Average_Yield=("Yield_Tonnes_Ha", "mean"),
    Total_Production=("Production_Tonnes", "sum"),
    Average_Profit=("Profit_INR", "mean"),
    Total_Profit=("Profit_INR", "sum"),
    Average_Water_Used=("Water_Used_m3", "mean")
).round(2)

season_metrics

# Compare crop performance within each season

crop_season_summary = (
    df.groupby(["Season", "Crop"])
    .agg(
        Average_Yield=("Yield_Tonnes_Ha", "mean"),
        Average_Profit=("Profit_INR", "mean"),
        Average_Water_Efficiency=("Water_Efficiency_t_per_1000m3", "mean"),
    )
    .round(2)
    .sort_values(["Season", "Average_Yield"], ascending=[True, False])
)
crop_season_summary

# Analysis 1: Regional Differences

# Student Analysis 1
# Question: How does average crop yield differ across states?

state_yield = df.groupby('State')['Yield_Tonnes_Ha'].mean().sort_values(ascending=False)

print("Average Yield by State:")
print(state_yield)

state_yield.plot(kind='bar',
                 figsize=(10,5),
                 title='Average Crop Yield by State',
                 xlabel='State',
                 ylabel='Average Yield (Tonnes/Ha)',
                 rot=45)
# Why is it relevant?
# This analysis helps identify regional differences in agricultural productivity and shows which states have comparatively higher or lower average crop yields.

# Student Analysis 2
# Question: How does crop yield vary across different seasons?

crop_season_yield = df.groupby(['Crop', 'Season'])['Yield_Tonnes_Ha'].mean().unstack()

print("Average Yield by Crop and Season:")
print(crop_season_yield)

crop_season_yield.plot(kind='bar',
                       figsize=(12,6),
                       title='Crop Yield Across Different Seasons',
                       xlabel='Crop',
                       ylabel='Average Yield (Tonnes/Ha)',
                       rot=45)
# Why is it relevant?
# This analysis identifies seasonal patterns in crop productivity and helps understand which seasons are associated with better yield for different crops.

# Student Analysis 3
# Question: How does irrigation method affect water-use efficiency?

irrigation_efficiency = df.groupby('Irrigation_Method')[
    'Water_Efficiency_t_per_1000m3'
].mean().sort_values(ascending=False)

print("Average Water Efficiency by Irrigation Method:")
print(irrigation_efficiency)

irrigation_efficiency.plot(kind='bar',
                           figsize=(8,5),
                           title='Water Efficiency by Irrigation Method',
                           xlabel='Irrigation Method',
                           ylabel='Water Efficiency (Tonnes per 1000 m³)',
                           rot=0)
# Why is it relevant?
# This analysis compares irrigation methods based on water efficiency and helps understand differences in agricultural water utilization.

"""**CONCLUSION **

1. **Crop Yield and Seasonal Rainfall**
*Observation:* High rainfall seasons correlate with a significant increase in corn yields compared to dry seasons.
*Evidence*: The line chart of "Seasonal Yield vs. Rainfall" shows corn yields peaking at 150 bushels/acre when seasonal rainfall exceeds 30 inches.
*Interpretation*: Corn is highly sensitive to moisture levels and thrives during high-precipitation periods.
*Limitation:* It should not be assumed that adding more water indefinitely will continue to increase yields, as flooding or waterlogging limits were not analyzed.


---


2. **Fertilizer Efficiency PlateauObservation**:
*Observation: *Increasing nitrogen fertilizer application past a certain threshold does not result in a linear increase in wheat yield.
*Evidence*: The scatter plot of "Yield vs. Fertilizer Input" shows a flattening curve (diminishing returns) after 120 lbs of nitrogen per acre.
*Interpretation:* There is an optimal chemical saturation point for soil nutrients beyond which plants cannot absorb more.
*Limitation*: This finding may only apply to the specific soil types present in this dataset and might differ for other regions.


---


3. **Temperature Stress on Specific CropsObservation**:
 *Obervation*: Soybeans show a sharp drop in overall performance during sustained high-temperature weeks.
 *Evidence*: The correlation matrix indicates a negative correlation coefficient (-0.65) between average weekly temperatures above 95°F and soybean health indices.
 *Interpretation*: Extreme heat stress negatively impacts the vegetative or reproductive stages of soybean growth.
 *Limitation*: The analysis only shows a negative association; it cannot prove heat alone caused the drop without controlling for accompanying factors like drought.


---


 4. **Soil pH and Nutrient Absorption:**
 *Observation*: Fields with highly acidic soil yield significantly lower quantities of legumes.
 *Evidence:* The bar graph comparing "Soil pH Categories vs. Total Yield" shows a 40% reduction in harvest volume for fields with a pH below
 *Interpretation*: Acidic soil conditions likely restrict the availability of essential nutrients required for legume growth.
 *Limitation*: This dataset does not track lime treatments or soil remediation efforts that might mitigate these acidic effects.


---

5. **Pest Infestation and Harvest Timings:**
*Observation*: Crops harvested later in the autumn season show higher rates of pest damage.
*Evidence*: The distribution histogram for "Pest Damage Levels by Month" shows damage categories shifting from 'Low' in August to 'Severe' in late October.*Interpretation*: Prolonged exposure in the field provides a longer window for pest populations to multiply and damage crops.
*Limitation*: This association might be driven by seasonal migration patterns of specific insects rather than just the passage of time.


---


6. **Organic vs. Synthetic Fertilizer Yields:**
*Observation*: Synthetic fertilizer fields produce higher immediate volumes, while organic fields show more stable yields across fluctuating weather.*Evidence*: The box plot comparing fertilizer types shows a higher median yield for synthetic options, but a narrower interquartile range (lower variance) for organic options during dry years.
*Interpretation*: Organic fertilizers may improve soil water retention and resilience, offering better buffering during poor seasonal conditions.*Limitation: *The dataset does not account for the long-term cumulative effects of these fertilizers over multiple decades.


---


7. ** Regional Market Price Fluctuations:**
*Observation*: Crop market prices drop substantially during peak harvest months.*Evidence:* The time-series trend of "Monthly Market Prices" shows a consistent 25% price dip every year during September and October.
*Interpretation*: High seasonal supply during harvest periods temporarily floods the market, driving down local commodity prices.
*Limitation: *This trend assumes local storage limitations force immediate sales; it doesn't account for farmers who use grain silos to sell later.


---


8. **Crop Rotation Benefits Observation**:
*Obseravtion*: Fields that alternated between corn and soybeans over consecutive years maintain higher baseline yields.
*Evidence:* The historical field tracking data shows a 15% higher average yield in rotated fields compared to continuous mono-cropping corn fields.*Interpretation:* Crop rotation helps break pest cycles and naturally replenishes soil nutrients like nitrogen.
*Limitation*: This finding does not factor in the variable economic costs of switching equipment and seeds required to manage two different crop systems.
"""